/**
 * ParceLLA — Deal Sharing & Permalinks
 *
 * Generates shareable deal links that encode:
 *   - Site ID
 *   - Model overrides (exit cap, hard cost, etc.)
 *   - Waterfall preset
 *   - Expiry (optional)
 *
 * Share targets:
 *   - Permalink URL (copy to clipboard)
 *   - Email with deal summary
 *   - LP package (PDF + assumptions)
 *
 * Backend routes (add to api/routes/other.js):
 *   POST /api/share           — create share token
 *   GET  /api/share/:token    — resolve token → site + overrides
 */

// ── Client-side share link builder ────────────────────────────────────────────
const BASE_URL = import.meta?.env?.VITE_APP_URL ?? 'https://parcella.com';

/**
 * Build a shareable URL encoding site + overrides as URL params
 * No server round-trip needed for basic sharing
 */
export function buildShareURL(siteId, overrides = {}, options = {}) {
  const params = new URLSearchParams();
  params.set('site', siteId);

  // Encode overrides compactly
  if (overrides.exitCap)  params.set('ec', overrides.exitCap);
  if (overrides.hcpsf)    params.set('hc', overrides.hcpsf);
  if (overrides.sc)       params.set('sc', overrides.sc);
  if (overrides.ppu)      params.set('pu', overrides.ppu);
  if (overrides.method)   params.set('m',  overrides.method);
  if (options.preset)     params.set('wf', options.preset);
  if (options.tab)        params.set('tab', options.tab);

  return `${BASE_URL}/deal?${params.toString()}`;
}

/**
 * Parse a share URL back into siteId + overrides
 */
export function parseShareURL(url) {
  const params = new URL(url).searchParams;
  const siteId = +params.get('site');
  const overrides = {};
  if (params.get('ec'))  overrides.exitCap = +params.get('ec');
  if (params.get('hc'))  overrides.hcpsf   = +params.get('hc');
  if (params.get('sc'))  overrides.sc      = +params.get('sc');
  if (params.get('pu'))  overrides.ppu     = +params.get('pu');
  if (params.get('m'))   overrides.method  = params.get('m');
  const preset = params.get('wf') ?? 'institutional';
  const tab    = params.get('tab') ?? 'overview';
  return { siteId, overrides, preset, tab };
}

/**
 * Copy share link to clipboard with toast feedback
 */
export async function copyShareLink(siteId, overrides = {}, options = {}) {
  const url = buildShareURL(siteId, overrides, options);
  try {
    await navigator.clipboard.writeText(url);
    return { success: true, url };
  } catch {
    // Fallback for older browsers
    const el = document.createElement('textarea');
    el.value = url;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    return { success: true, url };
  }
}

/**
 * Build email share body for a deal
 */
export function buildShareEmail(site, model, options = {}) {
  const url   = buildShareURL(site.id, options.overrides ?? {}, options);
  const fmtM  = n => n >= 1e6 ? '$' + (Math.round(n/1e5)/10) + 'M'
                   : n >= 1e3 ? '$' + Math.round(n/1e3) + 'K'
                   : '$' + Math.round(n);

  const subject = `ParceLLA Deal: ${site.addr} — ${model.irrV}% IRR, ${fmtM(model.netProfit)} profit`;

  const body = `
${site.addr}
${site.hood}, Los Angeles · ${site.zone} · ${site.units} units

KEY METRICS
───────────
Net profit:     ${fmtM(model.netProfit)}
Levered IRR:    ${model.irrV}%
Dev spread:     ${model.devSpreadPct}%
Cap on cost:    ${model.capOnCost}%
All-in cost:    ${fmtM(model.total)}
Exit value:     ${fmtM(model.exitValue)} @ ${(model.exitCap * 100).toFixed(2)}% cap

DEAL LINK
─────────
${url}

Generated by ParceLLA · parcella.com
  `.trim();

  return {
    subject,
    body,
    mailto: `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,
  };
}

// ── Server-side: persistent share tokens ─────────────────────────────────────
// Add to api/routes/other.js:

export const shareRoutes = `
// POST /api/share — create persistent share token
shareRouter.post('/', async (req, res, next) => {
  try {
    const { siteId, overrides = {}, preset = 'institutional',
            expiresInDays = 30, label = '' } = req.body;

    const token = crypto.randomUUID().replace(/-/g, '').slice(0, 12);
    const expiresAt = new Date(Date.now() + expiresInDays * 86400000);

    const { data, error } = await supabase.from('share_links').insert({
      token, site_id: siteId, overrides, preset, label,
      created_by: req.user?.id ?? null,
      expires_at: expiresAt.toISOString(),
      view_count: 0,
    }).select().single();

    if (error) throw error;
    res.json({ token, url: \`\${process.env.APP_URL}/deal/\${token}\`, expiresAt });
  } catch (err) { next(err); }
});

// GET /api/share/:token — resolve token
shareRouter.get('/:token', async (req, res, next) => {
  try {
    const { data, error } = await supabase
      .from('share_links')
      .select('*, sites(*)')
      .eq('token', req.params.token)
      .gt('expires_at', new Date().toISOString())
      .single();

    if (error || !data) return res.status(404).json({ error: 'Share link not found or expired' });

    // Increment view count
    await supabase.from('share_links')
      .update({ view_count: data.view_count + 1 }).eq('token', req.params.token);

    res.json({ site: data.sites, overrides: data.overrides, preset: data.preset });
  } catch (err) { next(err); }
});
`;

// ── Supabase table for share_links ────────────────────────────────────────────
export const shareLinksSchema = `
CREATE TABLE IF NOT EXISTS share_links (
  token       TEXT PRIMARY KEY,
  site_id     INTEGER REFERENCES sites(id) ON DELETE CASCADE,
  overrides   JSONB DEFAULT '{}',
  preset      TEXT DEFAULT 'institutional',
  label       TEXT,
  created_by  UUID REFERENCES profiles(id) ON DELETE SET NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  view_count  INTEGER DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX share_links_site_idx ON share_links(site_id);
ALTER TABLE share_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Share links are public readable" ON share_links FOR SELECT USING (true);
CREATE POLICY "Auth users can create share links" ON share_links FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' OR created_by IS NULL);
`;
