CREATE TABLE IF NOT EXISTS public.terms_acceptances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  terms_version TEXT NOT NULL,
  terms_digest TEXT NOT NULL,
  underwriting_projection_acknowledged BOOLEAN NOT NULL CHECK (underwriting_projection_acknowledged),
  independent_verification_acknowledged BOOLEAN NOT NULL CHECK (independent_verification_acknowledged),
  acceptance_method TEXT NOT NULL DEFAULT 'clickwrap',
  user_agent TEXT,
  accepted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, terms_version)
);

CREATE INDEX IF NOT EXISTS terms_acceptances_user_version_idx
  ON public.terms_acceptances (user_id, terms_version, accepted_at DESC);

ALTER TABLE public.terms_acceptances ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.terms_acceptances IS
  'Server-timestamped audit record of ParcelLA Terms and underwriting-risk clickwrap acceptance.';
