-- Durable one-time property purchases. Stripe webhook events remain the audit
-- trail, while this table is the canonical access entitlement.

CREATE TABLE IF NOT EXISTS public.property_entitlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  site_id TEXT NOT NULL,
  stripe_checkout_session_id TEXT NOT NULL UNIQUE,
  stripe_payment_intent_id TEXT,
  amount_paid INTEGER,
  currency TEXT NOT NULL DEFAULT 'usd',
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, site_id)
);

CREATE INDEX IF NOT EXISTS property_entitlements_user_idx
  ON public.property_entitlements (user_id, purchased_at DESC);

ALTER TABLE public.property_entitlements ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.property_entitlements IS
  'Permanent property-level access granted only after a verified paid Stripe Checkout session.';

-- Backfill prior paid property purchases from the immutable Stripe event log.
INSERT INTO public.property_entitlements (
  user_id,
  site_id,
  stripe_checkout_session_id,
  stripe_payment_intent_id,
  amount_paid,
  currency,
  purchased_at
)
SELECT DISTINCT ON (se.user_id, se.stripe_data->'metadata'->>'site_id')
  se.user_id,
  se.stripe_data->'metadata'->>'site_id',
  se.stripe_data->>'id',
  NULLIF(se.stripe_data->>'payment_intent', ''),
  NULLIF(se.stripe_data->>'amount_total', '')::INTEGER,
  COALESCE(NULLIF(se.stripe_data->>'currency', ''), 'usd'),
  se.processed_at
FROM public.subscription_events se
WHERE se.user_id IS NOT NULL
  AND COALESCE(se.stripe_data->'metadata'->>'purchase_kind', se.stripe_data->'metadata'->>'kind') = 'property'
  AND se.stripe_data->'metadata'->>'site_id' IS NOT NULL
  AND LOWER(COALESCE(se.stripe_data->>'payment_status', '')) = 'paid'
ORDER BY se.user_id, se.stripe_data->'metadata'->>'site_id', se.processed_at ASC
ON CONFLICT (user_id, site_id) DO NOTHING;
